name: pull request
on:
  pull_request:
    branches:
      - "main"

jobs:
  run-tests:
    name: run tests & linting
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v1

      - name: run tests & linter
        run: |
          npm ci --silent
          npm run lint
